services:
  rds:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpass
      - POSTGRES_DB=reactive-data
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local