spring:
  application:
    name: reactive-ms

  jackson:
    time-zone: ${TIMEZONE:America/Mexico_City}
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: tools.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
    default-property-inclusion: non_null
    serialization:
      order-map-entries-by-keys: true

  web:
    locale: ${APP_LOCALE:en}
    locale-resolver: fixed

  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
  mongodb:
    uri: mongodb://localhost:27017
    database: reactive-mongo

logging:
  level:
    com.fsociety.web:
      reactive.ms.app.config: trace