spring:
  application:
    name: reactive-ms

  jackson:
    time-zone: ${TIMEZONE:America/Mexico_City}
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: tools.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
    default-property-inclusion: non_null
    serialization:
      order-map-entries-by-keys: true

  web:
    locale: ${APP_LOCALE:en}
    locale-resolver: fixed
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reactive-data}
    username: ${DB_USER:localuser}
    password: ${DB_PASS:localpass}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql:////${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reactive-data}
    user: ${DB_USER:localuser}
    password: ${DB_PASS:localpass}

logging:
  level:
    com.fsociety.web:
      reactive.ms.app.config: trace